package projectmigrate

import (
	"bytes"
	"strings"
	"testing"
)

func TestRenderCompatibilityAssets(t *testing.T) {
	project := Project{
		ModulePath:   "git.lmq.io/kaopuvm/spider",
		SourceFamily: "v0.3.9-beta.1",
		ProductCode:  "oneops",
		ShortName:    "spider",
		APIVersion:   "v1",
	}
	paths, err := CompatibilityAssetPaths(project.SourceFamily)
	if err != nil {
		t.Fatal(err)
	}
	if len(paths) != 7 {
		t.Fatalf("CompatibilityAssetPaths() returned %d paths, want 7", len(paths))
	}

	rendered := make(map[string][]byte, len(paths))
	for _, relativePath := range paths {
		body, err := RenderCompatibilityAsset(project, relativePath, "0.4.0")
		if err != nil {
			t.Fatalf("RenderCompatibilityAsset(%q) error = %v", relativePath, err)
		}
		if bytes.Contains(body, []byte("{{")) || bytes.Contains(body, []byte("}}")) {
			t.Fatalf("RenderCompatibilityAsset(%q) left a template expression", relativePath)
		}
		if !bytes.HasPrefix(body, []byte(`// Code generated by "grpc-kit-cli/0.4.0". DO NOT EDIT.`)) &&
			!bytes.HasPrefix(body, []byte(`# Code generated by "grpc-kit-cli/0.4.0". DO NOT EDIT.`)) {
			t.Fatalf("RenderCompatibilityAsset(%q) has an unexpected marker", relativePath)
		}
		rendered[relativePath] = body
	}

	assertAssetContains(t, rendered, "cmd/server/main.go", "handler.NewMicroservice(ctx, lc)")
	assertAssetContains(t, rendered, "handler/microservice.go", `"log/slog"`, "lc.Init(ctx)", "m.thisCfg.Init(ctx, opts...)")
	assertAssetContains(t, rendered, "handler/register.go", "HTTPHandlerFrontend(ctx, mux", "StartBackground(ctx)", "RegisterOneopsSpiderServer")
	assertAssetNotContains(t, rendered, "handler/register.go", "privateMCPHandle", "modeler/mcp")
	assertAssetContains(t, rendered, "handler/shutdown.go", "WarnContext(ctx", "Deregister(ctx)")
	assertAssetContains(t, rendered, independentOptionPath, `"log/slog"`, `"git.lmq.io/kaopuvm/spider/modeler/ent"`, `flow.NewClient(logger, fcc)`)
	assertAssetNotContains(t, rendered, independentOptionPath, "logrus")
	assertAssetContains(t, rendered, "scripts/env", "CLI_VERSION=0.4.0", "PRODUCT_CODE=oneops", "SHORT_NAME=spider")
}

func TestCompatibilityAssetPathsKeepV038WriteSetNarrow(t *testing.T) {
	paths, err := CompatibilityAssetPaths("v0.3.8")
	if err != nil {
		t.Fatal(err)
	}
	if len(paths) != 6 {
		t.Fatalf("CompatibilityAssetPaths() returned %d paths, want 6", len(paths))
	}
	for _, relativePath := range paths {
		if relativePath == independentOptionPath {
			t.Fatalf("v0.3.8 paths unexpectedly contain %s", independentOptionPath)
		}
	}
}

func TestRenderCompatibilityAssetRejectsUnsupportedInputs(t *testing.T) {
	project := Project{
		ModulePath:   "example.com/acme/service",
		SourceFamily: "v0.3.8",
		ProductCode:  "acme",
		ShortName:    "demo",
		APIVersion:   "v1",
	}
	tests := []struct {
		name    string
		project Project
		path    string
		version string
	}{
		{name: "unknown path", project: project, path: "handler/private.go", version: "0.4.0"},
		{name: "path from another source family", project: project, path: independentOptionPath, version: "0.4.0"},
		{name: "development target", project: project, path: "handler/shutdown.go", version: "0.0.0"},
		{name: "unknown source family", project: func() Project { p := project; p.SourceFamily = "v0.4.0"; return p }(), path: "handler/shutdown.go", version: "0.4.0"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if _, err := RenderCompatibilityAsset(test.project, test.path, test.version); err == nil {
				t.Fatal("RenderCompatibilityAsset() error = nil")
			}
		})
	}
}

func TestRenderCompatibilityAssetAllowsPrereleasePreview(t *testing.T) {
	project := Project{
		ModulePath:   "example.com/acme/service",
		SourceFamily: "v0.3.8",
		ProductCode:  "acme",
		ShortName:    "demo",
		APIVersion:   "v1",
	}
	body, err := RenderCompatibilityAsset(project, "handler/shutdown.go", "0.4.0-beta.1")
	if err != nil {
		t.Fatalf("RenderCompatibilityAsset() error = %v", err)
	}
	if !bytes.HasPrefix(body, []byte(`// Code generated by "grpc-kit-cli/0.4.0-beta.1". DO NOT EDIT.`)) {
		t.Fatalf("RenderCompatibilityAsset() marker = %q", firstLine(body))
	}
}

func TestCompatibilityAssetPathsReturnsCopy(t *testing.T) {
	first, err := CompatibilityAssetPaths("v0.3.8")
	if err != nil {
		t.Fatal(err)
	}
	first[0] = "changed"
	second, err := CompatibilityAssetPaths("v0.3.8")
	if err != nil {
		t.Fatal(err)
	}
	if second[0] == "changed" {
		t.Fatal("CompatibilityAssetPaths returned mutable package state")
	}
}

func assertAssetContains(t *testing.T, assets map[string][]byte, relativePath string, values ...string) {
	t.Helper()
	body := string(assets[relativePath])
	for _, value := range values {
		if !strings.Contains(body, value) {
			t.Errorf("%s does not contain %q", relativePath, value)
		}
	}
}

func assertAssetNotContains(t *testing.T, assets map[string][]byte, relativePath string, values ...string) {
	t.Helper()
	body := string(assets[relativePath])
	for _, value := range values {
		if strings.Contains(body, value) {
			t.Errorf("%s unexpectedly contains %q", relativePath, value)
		}
	}
}
