// Copyright © 2026 The gRPC Kit Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package projectmigrate

import (
	"fmt"
	"strings"
)

const (
	goMarkerPrefix     = `// Code generated by "grpc-kit-cli/`
	scriptMarkerPrefix = `# Code generated by "grpc-kit-cli/`
	markerSuffix       = `". DO NOT EDIT.`
)

var supportedSourceVersions = map[string]string{
	"0.3.8-beta.1": "v0.3.8",
	"0.3.8":        "v0.3.8",
	"0.3.9-beta.1": "v0.3.9-beta.1",
}

// Marker is a strict first-line grpc-kit-cli ownership declaration.
type Marker struct {
	Version       string
	SourceFamily  string
	CommentPrefix string
}

// ParseMarkerLine parses an exact Go or script marker. Similar comments,
// placeholders and non-canonical versions do not grant write ownership.
func ParseMarkerLine(line string) (Marker, error) {
	line = strings.TrimSuffix(line, "\r")
	prefix := ""
	switch {
	case strings.HasPrefix(line, goMarkerPrefix):
		prefix = "//"
		line = strings.TrimPrefix(line, goMarkerPrefix)
	case strings.HasPrefix(line, scriptMarkerPrefix):
		prefix = "#"
		line = strings.TrimPrefix(line, scriptMarkerPrefix)
	default:
		return Marker{}, fmt.Errorf("first line is not an exact grpc-kit-cli marker")
	}
	if !strings.HasSuffix(line, markerSuffix) {
		return Marker{}, fmt.Errorf("marker is missing the exact suffix %q", markerSuffix)
	}
	rawVersion := strings.TrimSuffix(line, markerSuffix)
	version, err := normalizeVersion(rawVersion)
	if err != nil {
		return Marker{}, fmt.Errorf("invalid marker version: %w", err)
	}

	return Marker{
		Version:       version,
		SourceFamily:  supportedSourceVersions[version],
		CommentPrefix: prefix,
	}, nil
}

// Supported reports whether the marker maps to a frozen source family.
func (m Marker) Supported() bool {
	return m.SourceFamily != ""
}
