package projectmigrate

import "testing"

func TestParseMarkerLine(t *testing.T) {
	tests := []struct {
		name    string
		line    string
		version string
		family  string
		comment string
		wantErr bool
	}{
		{
			name:    "Go stable source",
			line:    `// Code generated by "grpc-kit-cli/v0.3.8". DO NOT EDIT.`,
			version: "0.3.8",
			family:  "v0.3.8",
			comment: "//",
		},
		{
			name:    "script prerelease source with CRLF",
			line:    "# Code generated by \"grpc-kit-cli/0.3.9-beta.1\". DO NOT EDIT.\r",
			version: "0.3.9-beta.1",
			family:  "v0.3.9-beta.1",
			comment: "#",
		},
		{
			name:    "valid but unsupported source",
			line:    `// Code generated by "grpc-kit-cli/0.4.0". DO NOT EDIT.`,
			version: "0.4.0",
			comment: "//",
		},
		{name: "placeholder", line: `// Code generated by "grpc-kit-cli/{{ .Global.ReleaseVersion }}". DO NOT EDIT.`, wantErr: true},
		{name: "missing period", line: `// Code generated by "grpc-kit-cli/0.3.8". DO NOT EDIT`, wantErr: true},
		{name: "leading space", line: ` // Code generated by "grpc-kit-cli/0.3.8". DO NOT EDIT.`, wantErr: true},
		{name: "build metadata", line: `// Code generated by "grpc-kit-cli/0.3.8+local". DO NOT EDIT.`, wantErr: true},
		{name: "trailing newline", line: "// Code generated by \"grpc-kit-cli/0.3.8\". DO NOT EDIT.\n", wantErr: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			marker, err := ParseMarkerLine(test.line)
			if (err != nil) != test.wantErr {
				t.Fatalf("ParseMarkerLine() error = %v, wantErr %v", err, test.wantErr)
			}
			if test.wantErr {
				return
			}
			if marker.Version != test.version || marker.SourceFamily != test.family || marker.CommentPrefix != test.comment {
				t.Fatalf("ParseMarkerLine() = %#v, want version=%q family=%q comment=%q", marker, test.version, test.family, test.comment)
			}
			if marker.Supported() != (test.family != "") {
				t.Fatalf("Marker.Supported() = %v, family = %q", marker.Supported(), test.family)
			}
		})
	}
}
