package projectmigrate

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

const validEnvironment = `# Code generated by "grpc-kit-cli/0.3.9-beta.1". DO NOT EDIT.
#
# identity
CLI_VERSION=0.3.9-beta.1
PRODUCT_CODE=oneops
SHORT_NAME=spider
API_VERSION=v1
APPNAME=${PRODUCT_CODE}-${SHORT_NAME}-${API_VERSION}
SERVICE_CODE=${SHORT_NAME}.${API_VERSION}.${PRODUCT_CODE}
`

func TestLoadProject(t *testing.T) {
	root := writeProject(t, validEnvironment, "module git.lmq.io/kaopuvm/spider\n\ngo 1.25.0\n")

	project, err := LoadProject(root)
	if err != nil {
		t.Fatalf("LoadProject() error = %v", err)
	}
	if project.Root != root {
		t.Fatalf("Root = %q, want %q", project.Root, root)
	}
	if project.ModulePath != "git.lmq.io/kaopuvm/spider" ||
		project.SourceCLIVersion != "0.3.9-beta.1" ||
		project.SourceFamily != "v0.3.9-beta.1" ||
		project.ProductCode != "oneops" ||
		project.ShortName != "spider" ||
		project.APIVersion != "v1" {
		t.Fatalf("LoadProject() = %#v", project)
	}
}

func TestLoadProjectRejectsInvalidEnvironment(t *testing.T) {
	tests := []struct {
		name    string
		replace string
		with    string
		want    string
	}{
		{name: "marker mismatch", replace: "CLI_VERSION=0.3.9-beta.1", with: "CLI_VERSION=0.3.8", want: "does not match"},
		{name: "duplicate", replace: "PRODUCT_CODE=oneops", with: "PRODUCT_CODE=oneops\nPRODUCT_CODE=oneops", want: "duplicates PRODUCT_CODE"},
		{name: "shell expansion", replace: "SHORT_NAME=spider", with: "SHORT_NAME=$(hostname)", want: "non-literal"},
		{name: "unsupported assignment", replace: "API_VERSION=v1", with: "API_VERSION=v1\nEXTRA=value", want: "unsupported key"},
		{name: "invalid product", replace: "PRODUCT_CODE=oneops", with: "PRODUCT_CODE=OneOps", want: "PRODUCT_CODE"},
		{name: "invalid API version", replace: "API_VERSION=v1", with: "API_VERSION=latest", want: "API_VERSION"},
		{name: "changed derived value", replace: "APPNAME=${PRODUCT_CODE}-${SHORT_NAME}-${API_VERSION}", with: "APPNAME=oneops-spider-v1", want: "unexpected derived value"},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			environment := strings.Replace(validEnvironment, test.replace, test.with, 1)
			root := writeProject(t, environment, "module git.lmq.io/kaopuvm/spider\n")
			_, err := LoadProject(root)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("LoadProject() error = %v, want containing %q", err, test.want)
			}
		})
	}
}

func TestLoadProjectRejectsInvalidGoMod(t *testing.T) {
	root := writeProject(t, validEnvironment, "go 1.25.0\n")
	_, err := LoadProject(root)
	if err == nil || !strings.Contains(err.Error(), "module path is missing") {
		t.Fatalf("LoadProject() error = %v, want missing module path", err)
	}
}

func TestLoadProjectRejectsSymlinkedIdentityFile(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("symlink behavior requires elevated privileges on some Windows hosts")
	}
	root := writeProject(t, validEnvironment, "module git.lmq.io/kaopuvm/spider\n")
	target := filepath.Join(root, "actual-env")
	if err := os.WriteFile(target, []byte(validEnvironment), 0o600); err != nil {
		t.Fatal(err)
	}
	environmentPath := filepath.Join(root, "scripts", "env")
	if err := os.Remove(environmentPath); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(target, environmentPath); err != nil {
		t.Fatal(err)
	}

	_, err := LoadProject(root)
	if err == nil || !strings.Contains(err.Error(), "not a symlink") {
		t.Fatalf("LoadProject() error = %v, want symlink rejection", err)
	}
}

func writeProject(t *testing.T, environment, goMod string) string {
	t.Helper()
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "scripts", "env"), []byte(environment), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte(goMod), 0o600); err != nil {
		t.Fatal(err)
	}
	return root
}
