package projectmigrate

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"os"
	"testing"
	"text/template"

	_ "embed"
)

//go:embed testdata/legacy-v0.3.8-generate.sh
var legacyGenerateScriptFixture []byte

func TestLegacyGenerateScriptFixtureDigest(t *testing.T) {
	digest := fmt.Sprintf("%x", sha256.Sum256(legacyGenerateScriptFixture))
	if digest != legacyGenerateScriptV038SHA256 {
		t.Fatalf("legacy fixture digest = %s, want %s", digest, legacyGenerateScriptV038SHA256)
	}
	if !bytes.HasPrefix(legacyGenerateScriptFixture, []byte("#!/bin/bash\n")) {
		t.Fatal("legacy fixture must keep the shebang on line 1")
	}
	if bytes.Contains(legacyGenerateScriptFixture, []byte(`-I "${GOPATH}"/include/`)) {
		t.Fatal("legacy fixture must predate the ${GOPATH}/include include path")
	}
	if !bytes.Contains(legacyGenerateScriptFixture, []byte(`-I /usr/local/include/`)) {
		t.Fatal("legacy fixture must rely on /usr/local/include")
	}
}

func TestGenerateScriptAsset(t *testing.T) {
	if !bytes.HasPrefix(generateScriptAsset, []byte("#!/bin/bash\n")) {
		t.Fatal("frozen asset must keep the shebang on line 1")
	}
	if markerLine := secondLine(generateScriptAsset); markerLine != `# Code generated by "grpc-kit-cli/{{ .TargetCLIVersion }}". DO NOT EDIT.` {
		t.Fatalf("frozen asset line 2 = %q, want the version marker expression", markerLine)
	}
	digest := fmt.Sprintf("%x", sha256.Sum256(generateScriptAsset))
	if digest != generateScriptAssetSHA256 {
		t.Fatalf("frozen asset digest = %s, want %s", digest, generateScriptAssetSHA256)
	}
}

func TestRenderGenerateScriptTarget(t *testing.T) {
	target, err := renderGenerateScriptTarget("0.4.0")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.HasPrefix(target, []byte("#!/bin/bash\n")) {
		t.Fatal("rendered target must keep the shebang on line 1")
	}
	marker, err := ParseMarkerLine(secondLine(target))
	if err != nil {
		t.Fatalf("rendered target line 2 does not parse as a script marker: %v", err)
	}
	if marker.Version != "0.4.0" || marker.CommentPrefix != "#" {
		t.Fatalf("rendered target marker = %#v, want version 0.4.0 with # prefix", marker)
	}
	for _, include := range []string{`-I "${GOPATH}"/include/ \`, `-I /usr/local/include/ \`} {
		if count := bytes.Count(target, []byte(include)); count != 2 {
			t.Fatalf("include %q appears %d times, want 2 (both protoc calls)", include, count)
		}
	}
	if bytes.Contains(target, []byte("{{")) || bytes.Contains(target, []byte("}}")) {
		t.Fatal("rendered target must not retain template expressions")
	}
	if _, err := renderGenerateScriptTarget("not-a-version"); err == nil {
		t.Fatal("renderGenerateScriptTarget() accepted an invalid version")
	}
}

func TestGenerateScriptAssetMatchesServiceTemplate(t *testing.T) {
	// Conscious-sync guard: changing template/service/scripts/generate.sh.tmpl
	// requires re-freezing the embedded asset and generateScriptAssetSHA256.
	templateBody, err := os.ReadFile("../../template/service/scripts/generate.sh.tmpl")
	if err != nil {
		t.Fatal(err)
	}
	tmpl, err := template.New("service-template").Option("missingkey=error").Parse(string(templateBody))
	if err != nil {
		t.Fatal(err)
	}
	var rendered bytes.Buffer
	if err := tmpl.Execute(&rendered, map[string]any{
		"Global": map[string]any{"ReleaseVersion": "0.4.0"},
	}); err != nil {
		t.Fatal(err)
	}
	target, err := renderGenerateScriptTarget("0.4.0")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(rendered.Bytes(), target) {
		t.Fatal("embedded asset drifted from template/service/scripts/generate.sh.tmpl; re-freeze the asset and digest")
	}
}

func TestPlanGenerateScriptStates(t *testing.T) {
	target, err := renderGenerateScriptTarget("0.4.0")
	if err != nil {
		t.Fatal(err)
	}
	other, err := renderGenerateScriptTarget("0.5.1")
	if err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		name     string
		body     []byte
		mode     os.FileMode
		target   []byte
		wantUpTo bool
		wantPath string
	}{
		{name: "legacy content rewrites", body: legacyGenerateScriptFixture, mode: 0o755, target: target, wantPath: generateScriptPath},
		{name: "current content is up to date", body: target, mode: 0o640, target: target, wantUpTo: true},
		{name: "other marker version defers to manual action", body: other, mode: 0o755, target: target},
		{name: "unknown content defers to manual action", body: append(bytes.Clone(legacyGenerateScriptFixture), []byte("# local edit\n")...), mode: 0o755, target: target},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			change, upToDate := planGenerateScript(test.body, test.mode, test.target)
			if upToDate != test.wantUpTo {
				t.Fatalf("planGenerateScript() upToDate = %v, want %v", upToDate, test.wantUpTo)
			}
			if test.wantPath == "" {
				if change != nil {
					t.Fatalf("planGenerateScript() change = %#v, want nil", change)
				}
				return
			}
			if change == nil {
				t.Fatal("planGenerateScript() change = nil, want a rewrite")
			}
			if change.Path != test.wantPath {
				t.Fatalf("change.Path = %q, want %q", change.Path, test.wantPath)
			}
			if change.Mode != test.mode {
				t.Fatalf("change.Mode = %v, want %v", change.Mode, test.mode)
			}
			if !bytes.Equal(change.Before, test.body) {
				t.Fatal("change.Before does not preserve the on-disk content")
			}
			if !bytes.Equal(change.After, test.target) {
				t.Fatal("change.After does not equal the rendered target")
			}
			if digest := fmt.Sprintf("%x", change.BeforeSHA256); digest != fmt.Sprintf("%x", sha256.Sum256(test.body)) {
				t.Fatal("change.BeforeSHA256 does not match the on-disk content")
			}
		})
	}
}

func TestScanGenerateScriptAction(t *testing.T) {
	root := writeProject(t, validEnvironment, "module git.lmq.io/kaopuvm/spider\n")
	project, err := LoadProject(root)
	if err != nil {
		t.Fatal(err)
	}
	scriptPath := root + "/scripts/generate.sh"
	target, err := renderGenerateScriptTarget("0.4.0")
	if err != nil {
		t.Fatal(err)
	}

	collect := func(changedPaths map[string]struct{}) []Diagnostic {
		t.Helper()
		var actions []Diagnostic
		dedup := make(map[string]struct{})
		if err := scanGenerateScriptAction(project, changedPaths, &actions, dedup, "0.4.0"); err != nil {
			t.Fatal(err)
		}
		return actions
	}

	if actions := collect(nil); len(actions) != 0 {
		t.Fatalf("absent file produced actions: %#v", actions)
	}

	if err := os.WriteFile(scriptPath, legacyGenerateScriptFixture, 0o755); err != nil {
		t.Fatal(err)
	}
	if actions := collect(nil); len(actions) != 0 {
		t.Fatalf("legacy content produced actions: %#v", actions)
	}
	if err := os.WriteFile(scriptPath, target, 0o755); err != nil {
		t.Fatal(err)
	}
	if actions := collect(nil); len(actions) != 0 {
		t.Fatalf("current content produced actions: %#v", actions)
	}

	if err := os.WriteFile(scriptPath, append(bytes.Clone(legacyGenerateScriptFixture), []byte("# local edit\n")...), 0o755); err != nil {
		t.Fatal(err)
	}
	if actions := collect(nil); !hasDiagnosticCode(actions, "generate_script_modified") {
		t.Fatalf("modified content produced no manual action: %#v", actions)
	}
	if err := os.WriteFile(scriptPath, append(bytes.Clone(target), []byte("# local edit\n")...), 0o755); err != nil {
		t.Fatal(err)
	}
	if actions := collect(nil); !hasDiagnosticCode(actions, "generate_script_modified") {
		t.Fatalf("modified marker-carrying content produced no manual action: %#v", actions)
	}
	if actions := collect(map[string]struct{}{generateScriptPath: {}}); len(actions) != 0 {
		t.Fatalf("planned rewrite still produced a manual action: %#v", actions)
	}
}

func TestPlanGenerateScriptDoesNotMutateTarget(t *testing.T) {
	target, err := renderGenerateScriptTarget("0.4.0")
	if err != nil {
		t.Fatal(err)
	}
	before := bytes.Clone(target)
	if _, upToDate := planGenerateScript(legacyGenerateScriptFixture, 0o755, target); upToDate {
		t.Fatal("legacy content reported up to date")
	}
	if !bytes.Equal(target, before) {
		t.Fatal("planGenerateScript mutated the rendered target")
	}
}
