package projectmigrate

import "testing"

const legacyPublicEmbedFixture = `// Code generated by "grpc-kit-cli/{{ .Global.ReleaseVersion }}". DO NOT EDIT.

package public

import (
	"embed"
)

//go:embed admin/*
//go:embed openapi/*
//go:embed webroot/*
var Assets embed.FS
`

func TestSpiderSourceFixture(t *testing.T) {
	fixture := SpiderSourceFixture()
	if fixture.Commit != spiderFixtureCommit || fixture.ProjectCLIVersion != "0.3.9-beta.1" || len(fixture.Files) != 6 {
		t.Fatalf("SpiderSourceFixture() = %#v", fixture)
	}
	fixture.Files[legacyPublicEmbedPath] = "changed"
	if SpiderSourceFixture().Files[legacyPublicEmbedPath] != legacyPublicEmbedSHA256 {
		t.Fatal("SpiderSourceFixture returned mutable package state")
	}
}

func TestCLIV038SourceFixture(t *testing.T) {
	fixture := CLIV038SourceFixture()
	if fixture.Commit != cliV038FixtureCommit || fixture.ProjectCLIVersion != "0.3.8" || len(fixture.Files) != 6 {
		t.Fatalf("CLIV038SourceFixture() = %#v", fixture)
	}
	fixture.Files["scripts/env"] = "changed"
	if CLIV038SourceFixture().Files["scripts/env"] == "changed" {
		t.Fatal("CLIV038SourceFixture returned mutable package state")
	}
}

func TestGoChatSourceFixture(t *testing.T) {
	fixture := GoChatSourceFixture()
	if fixture.Commit != gochatFixtureCommit || fixture.ProjectCLIVersion != "0.3.9-beta.1" || len(fixture.Files) != 8 {
		t.Fatalf("GoChatSourceFixture() = %#v", fixture)
	}
	const independentOptionSHA256 = "ab9c17cfc71974101dab19696caa8d4e743781f9d5cf4fa64667ee1d5bb84239"
	if fixture.Files[independentOptionPath] != independentOptionSHA256 {
		t.Fatalf("GoChatSourceFixture()[%q] = %q", independentOptionPath, fixture.Files[independentOptionPath])
	}
	fixture.Files[independentOptionPath] = "changed"
	if GoChatSourceFixture().Files[independentOptionPath] != independentOptionSHA256 {
		t.Fatal("GoChatSourceFixture returned mutable package state")
	}
}

func TestIsKnownLegacyMarkerFile(t *testing.T) {
	if !IsKnownLegacyMarkerFile(legacyPublicEmbedPath, []byte(legacyPublicEmbedFixture)) {
		t.Fatal("exact frozen fixture was not recognized")
	}
	if IsKnownLegacyMarkerFile("other/embed.go", []byte(legacyPublicEmbedFixture)) {
		t.Fatal("fixture was recognized at another path")
	}
	if IsKnownLegacyMarkerFile(legacyPublicEmbedPath, []byte(legacyPublicEmbedFixture+"\n")) {
		t.Fatal("modified fixture was recognized")
	}
}
