// Copyright © 2026 The gRPC Kit Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package projectmigrate

import (
	"crypto/sha256"
	"fmt"
)

const (
	cliV038FixtureCommit    = "1270ce7cccf60ae3d9358d24cb48e84097b36c06"
	spiderFixtureCommit     = "a5af60793e996f8072d9c9444287c4059784b1bd"
	gochatFixtureCommit     = "f1cb0fad384736f5a7a597ae41729e8133408c2e"
	legacyPublicEmbedPath   = "public/embed.go"
	legacyPublicEmbedSHA256 = "43e669ebe9a037964f803ebe000e62f6c25e1876e2b3e2d1ca12f4d84444f040"
)

// SourceFixture records the immutable evidence used to select compatibility
// assets. SHA-256 values are over the exact Git blob contents at Commit.
type SourceFixture struct {
	Name              string
	Commit            string
	ProjectCLIVersion string
	Files             map[string]string
}

var spiderSourceFixture = SourceFixture{
	Name:              "spider",
	Commit:            spiderFixtureCommit,
	ProjectCLIVersion: "0.3.9-beta.1",
	Files: map[string]string{
		"scripts/env":             "ef67ba7a27e22429a52df0a4af61fac5ee983d4e0b5931c147372355104e6487",
		"cmd/server/main.go":      "8f166ff22d8e517fbd07ff65b024a01ed338f5e05c5d0ca053d27c88b2ebf77f",
		"handler/microservice.go": "42f27c20a3648187dbb328c87c9afe8d227ca72c7db73092ff482a83e0ac6125",
		"handler/rpc_internal.go": "7f81c06a15ad1cc6eeda776d0379c1a78e25cde1525345e08e3b5508604dfac4",
		"handler/shutdown.go":     "378dfa53f5658540c1c3e9514aa46d2a75437ced2f27ab2658dc5b964f5038ce",
		legacyPublicEmbedPath:     legacyPublicEmbedSHA256,
	},
}

var gochatSourceFixture = SourceFixture{
	Name:              "gochat",
	Commit:            gochatFixtureCommit,
	ProjectCLIVersion: "0.3.9-beta.1",
	Files: map[string]string{
		"scripts/env":             "df7a28d131e024a70400513649ebbf1e59a60f3a9a1b9755422b4934b4464b3f",
		"cmd/server/main.go":      "37cfc90fde3b5b038ea76daf0886f99ebff2e9ee4133067c7d35fcb8ef8af6c8",
		"handler/microservice.go": "38bace39a46d0029f1a7d69cad75b1bca072cc2bf9ff9eb4c621802858757dbc",
		"handler/register.go":     "5be4e83c41ab4b335030998091d3e8fffa5c963cf0c01fb4de0d91f90c3682e0",
		"handler/rpc_internal.go": "5c754df6558622824e1ad3331126829a46a47bfd101a49b1148b6a86b5d200b1",
		"handler/shutdown.go":     "378dfa53f5658540c1c3e9514aa46d2a75437ced2f27ab2658dc5b964f5038ce",
		independentOptionPath:     "ab9c17cfc71974101dab19696caa8d4e743781f9d5cf4fa64667ee1d5bb84239",
		legacyPublicEmbedPath:     legacyPublicEmbedSHA256,
	},
}

var cliV038SourceFixture = SourceFixture{
	Name:              "cli-v0.3.8",
	Commit:            cliV038FixtureCommit,
	ProjectCLIVersion: "0.3.8",
	Files: map[string]string{
		"scripts/env":             "7b607e4fad4c595cb55971ddf7dec6637f4ed9519153c7b648b97ffe527ca3f8",
		"cmd/server/main.go":      "3a6cf1f1562bc53ab71d83f61033ba4ea7ffc654ab35c0680320e4ea8db625ae",
		"handler/microservice.go": "77b157cb720cb5920ca761d208fd4e3b9eeecfa5cecf9fe8143b89f20459c453",
		"handler/register.go":     "94ed7f786958baab11abdb39c55d4225c1229b9e6e849e0f611e5b5d2c237b33",
		"handler/rpc_internal.go": "4c11ed29dcd38ca5906b185459b47b6742ef3b4df0218b65acc7a923f577d509",
		"handler/shutdown.go":     "c10dd197feaba118b5340f9d1c50c0f049477a1c6f447b8c9d3b4e1d84220182",
	},
}

// CLIV038SourceFixture returns a defensive copy of the official v0.3.8
// template evidence.
func CLIV038SourceFixture() SourceFixture {
	return cloneSourceFixture(cliV038SourceFixture)
}

// SpiderSourceFixture returns a defensive copy of the frozen source evidence.
func SpiderSourceFixture() SourceFixture {
	return cloneSourceFixture(spiderSourceFixture)
}

// GoChatSourceFixture returns a defensive copy of the frozen source evidence
// for the v0.3.9-beta.1 generation that includes independent_option.go.
func GoChatSourceFixture() SourceFixture {
	return cloneSourceFixture(gochatSourceFixture)
}

func cloneSourceFixture(source SourceFixture) SourceFixture {
	fixture := source
	fixture.Files = make(map[string]string, len(source.Files))
	for path, digest := range source.Files {
		fixture.Files[path] = digest
	}
	return fixture
}

// IsKnownLegacyMarkerFile recognizes only the exact frozen public/embed.go
// output affected by the historical non-.tmpl generator bug.
func IsKnownLegacyMarkerFile(relativePath string, body []byte) bool {
	if relativePath != legacyPublicEmbedPath || firstLine(body) != `// Code generated by "grpc-kit-cli/{{ .Global.ReleaseVersion }}". DO NOT EDIT.` {
		return false
	}
	digest := sha256.Sum256(body)
	return fmt.Sprintf("%x", digest) == legacyPublicEmbedSHA256
}
