package cmd

import (
	"bytes"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/grpc-kit/pkg/vars"
)

func TestProjectMigrateRejectsExtraArguments(t *testing.T) {
	cmd := newRootCommand(func() error { return nil })
	cmd.SetOut(io.Discard)
	cmd.SetErr(io.Discard)
	cmd.SetArgs([]string{"project", "migrate", "one", "two"})

	if err := cmd.Execute(); err == nil {
		t.Fatal("Execute() error = nil, want an argument validation error")
	}
}

func TestProjectMigratePreviewAllowsPrereleaseVersion(t *testing.T) {
	previous := vars.ReleaseVersion
	vars.ReleaseVersion = "0.3.9-beta.1"
	t.Cleanup(func() { vars.ReleaseVersion = previous })

	cmd := newRootCommand(func() error { return nil })
	var output bytes.Buffer
	cmd.SetOut(&output)
	cmd.SetErr(io.Discard)
	cmd.SetArgs([]string{"project", "migrate", writeCommandTestProject(t)})

	if err := cmd.Execute(); err != nil {
		t.Fatalf("Execute() error = %v", err)
	}
	if !strings.Contains(output.String(), "Status: ready") || !strings.Contains(output.String(), "Apply blocked [release_version]") {
		t.Fatalf("output = %q", output.String())
	}
}

func TestProjectMigrateRejectsInvalidProject(t *testing.T) {
	previous := vars.ReleaseVersion
	vars.ReleaseVersion = "0.3.9-beta.1"
	t.Cleanup(func() { vars.ReleaseVersion = previous })

	cmd := newRootCommand(func() error { return nil })
	cmd.SetOut(io.Discard)
	cmd.SetErr(io.Discard)
	cmd.SetArgs([]string{"project", "migrate", t.TempDir()})

	err := cmd.Execute()
	if err == nil || !strings.Contains(err.Error(), "invalid project") {
		t.Fatalf("Execute() error = %v, want invalid project", err)
	}
}

func TestProjectMigrateRejectsUnsupportedSource(t *testing.T) {
	previous := vars.ReleaseVersion
	vars.ReleaseVersion = "0.3.9-beta.1"
	t.Cleanup(func() { vars.ReleaseVersion = previous })

	root := writeCommandTestProject(t)
	environmentPath := filepath.Join(root, "scripts", "env")
	body, err := os.ReadFile(environmentPath)
	if err != nil {
		t.Fatal(err)
	}
	body = []byte(strings.ReplaceAll(string(body), "0.3.9-beta.1", "0.4.0"))
	if err := os.WriteFile(environmentPath, body, 0o600); err != nil {
		t.Fatal(err)
	}

	cmd := newRootCommand(func() error { return nil })
	cmd.SetOut(io.Discard)
	cmd.SetErr(io.Discard)
	cmd.SetArgs([]string{"project", "migrate", root})

	err = cmd.Execute()
	if err == nil || !strings.Contains(err.Error(), "migration plan is unsupported") {
		t.Fatalf("Execute() error = %v, want unsupported source", err)
	}
}

func TestProjectMigrateApplyRejectsPrereleaseBuild(t *testing.T) {
	previous := vars.ReleaseVersion
	vars.ReleaseVersion = "0.3.9-beta.1"
	t.Cleanup(func() { vars.ReleaseVersion = previous })

	cmd := newRootCommand(func() error { return nil })
	cmd.SetOut(io.Discard)
	cmd.SetErr(io.Discard)
	cmd.SetArgs([]string{"project", "migrate", "--apply"})

	err := cmd.Execute()
	if err == nil || !strings.Contains(err.Error(), "refuse --apply") {
		t.Fatalf("Execute() error = %v, want prerelease apply refusal", err)
	}
}

func TestProjectMigrateApply(t *testing.T) {
	previous := vars.ReleaseVersion
	vars.ReleaseVersion = "0.4.0"
	t.Cleanup(func() { vars.ReleaseVersion = previous })

	root := writeCommandTestProject(t)
	for _, args := range [][]string{
		{"init"},
		{"add", "."},
		{"-c", "user.name=grpc-kit-test", "-c", "user.email=test@grpc-kit.invalid", "commit", "-m", "fixture"},
	} {
		command := exec.Command("git", append([]string{"-C", root}, args...)...)
		if output, err := command.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, output)
		}
	}

	cmd := newRootCommand(func() error { return nil })
	var output bytes.Buffer
	cmd.SetOut(&output)
	cmd.SetErr(io.Discard)
	cmd.SetArgs([]string{"project", "migrate", root, "--apply"})

	if err := cmd.Execute(); err != nil {
		t.Fatalf("Execute() error = %v\n%s", err, output.String())
	}
	if !strings.Contains(output.String(), "Managed files migrated: 1") {
		t.Fatalf("output = %q", output.String())
	}
	if !strings.Contains(output.String(), "Managed files migrated; project compatibility is not yet verified.") {
		t.Fatalf("output does not explain compatibility status: %q", output.String())
	}
	environment, err := os.ReadFile(filepath.Join(root, "scripts", "env"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(environment), "CLI_VERSION=0.4.0") {
		t.Fatalf("scripts/env was not migrated:\n%s", environment)
	}
}

func writeCommandTestProject(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "scripts"), 0o755); err != nil {
		t.Fatal(err)
	}
	environment := `# Code generated by "grpc-kit-cli/0.3.9-beta.1". DO NOT EDIT.
CLI_VERSION=0.3.9-beta.1
PRODUCT_CODE=oneops
SHORT_NAME=spider
API_VERSION=v1
APPNAME=${PRODUCT_CODE}-${SHORT_NAME}-${API_VERSION}
SERVICE_CODE=${SHORT_NAME}.${API_VERSION}.${PRODUCT_CODE}
`
	if err := os.WriteFile(filepath.Join(root, "scripts", "env"), []byte(environment), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module git.lmq.io/kaopuvm/spider\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	return root
}
