// Copyright © 2024 The gRPC Kit Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"bytes"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// updateCmd represents the version command
var updateCmd = &cobra.Command{
	Use:   "update",
	Short: "Update the application code template",
	Long:  `Updating the application code template generated by grpc-kit-cli to the current version.`,
	RunE:  runFuncUpdate,
}

func init() {
	// rootCmd.AddCommand(updateCmd)
}

func runFuncUpdate(cmd *cobra.Command, args []string) error {
	// 遍历当前目录所有文件
	// 获取当前目录下的 "scripts/env" 文件
	content, err := os.ReadFile("./scripts/env")
	if err != nil {
		return err
	}

	lines := bytes.Split(content, []byte("\n"))
	fmt.Println(string(lines[0]))

	return nil
}
