// Code generated by "grpc-kit-cli/{{ .Global.ReleaseVersion }}". DO NOT EDIT.

package public

import (
    "embed"
)

//go:embed admin/*
//go:embed openapi/*
//go:embed webroot/*
var Assets embed.FS
